### ISSUE TITLE
Making figure grid sections equal sizes

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/components-on-a-grid#3]
Hi @hannahdelaney,

I'm having an issue with making the two figures at the bottom of the grid be equal sizes. Currently, the first figure is taking up 1/3 of the grid and the second figure is taking up 2/3 of the grid. In my code, I've written that I want each section to take up 1/2 the grid but it's not translating onto the browser. Am I placing the grid-template-columns: repeat(2, 1fr) in the wrong spot to target the two figures?

Thanks,
Rianna
<img width="992" alt="Screen Shot 2020-09-23 at 9 46 49 AM" src="https://user-images.githubusercontent.com/55094049/94021947-93795680-fd82-11ea-9bb8-acd8abd84616.png">

**Comment by HannahDelaney** [comment]
Hey! Well spotted, yes the `grid-template-columns: repeat(2, 1fr)` needs to be on the body tag instead of the main. Your body tag is where the `display: grid` is defined so that's where you specify the column repeat.

Your spacing is also being a bit mixed up by the paddings in your nav, of all places! Since you're using fractions to move things around your grids, adding big paddings (you have your ul with `padding-top: 1rem;` and `padding-left: 12rem;`) will change the size of your fractions, so instead of being 50% they looked uneven for the 2 figures at the bottom. If you just remove those and give your ul `padding:0` it should look just perfect!
